#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   SWS STUDIO, apply

   Splices the generated base layer into each app's inline <style> block.

     node design/apply.mjs            all apps
     node design/apply.mjs qr-maker   one app
     node design/apply.mjs --check    report what would change, write nothing

   WHY INLINE, and not a shared stylesheet everyone links to:

   Each app is an offline-first PWA whose service worker is registered at
   /<app>/ and therefore only intercepts requests inside its own scope. A
   shared /studio.css would sit outside every scope, so it would never be
   served from cache, and the apps would lose their styling the moment the
   user went offline. That is the whole promise broken for a cosmetic saving.
   Inline also means no extra request and no flash of unstyled content.

   The cost is 23 copies, which is exactly what this script exists to manage.
   Edit design/studio.css or design/skins.mjs, rebuild, re-apply.

   The block is delimited by sentinel comments, so re-running replaces the base
   in place and never touches the app's own rules below it.
   ═══════════════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { SKINS } from './skins.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const APPS = join(HERE, '..', 'apps');

const BEGIN = '/* ▼▼▼ SWS STUDIO BASE, generated by design/build.mjs. Do not edit. ▼▼▼ */';
const END   = '/* ▲▲▲ END SWS STUDIO BASE ▲▲▲ */';
const APP_LAYER = '/* ═══ APP LAYER, rules specific to this app live below ═══ */';

/**
 * Remove the app's old `:root{...}` palette, and any dark-mode media query
 * that contained nothing but one.
 *
 * This has to happen, and it has to happen here. The app layer sits AFTER the
 * base in the cascade, so a leftover `:root{--bg:#f6f7f9}` would quietly stomp
 * the new token on every single app and the whole restyle would appear to do
 * nothing. Brace-matched rather than regexed, because a palette block contains
 * no nested braces but the media query wrapping it does.
 */
function stripLegacyTokens(css, baseNames){
  let out = '';
  let i = 0;

  while (i < css.length){
    const root = css.indexOf(':root', i);
    if (root === -1){ out += css.slice(i); break; }

    const open = css.indexOf('{', root);
    if (open === -1){ out += css.slice(i); break; }

    // find the matching close brace
    let depth = 0, end = -1;
    for (let j = open; j < css.length; j++){
      if (css[j] === '{') depth++;
      else if (css[j] === '}' && --depth === 0){ end = j; break; }
    }
    if (end === -1){ out += css.slice(i); break; }

    /* Only the declarations the base now owns get dropped. An app's OWN custom
       properties are kept and re-emitted.
       Specials Planner is why: its logo mark is
       `linear-gradient(135deg, var(--terra), var(--mustard))`, and deleting the
       whole :root turned that into a gradient between two undefined values, an invisible logo, in the one app that already looked good. */
    const survivors = css.slice(open + 1, end)
      .split(';')
      .map((d) => d.trim())
      .filter((d) => d.startsWith('--'))
      .filter((d) => !baseNames.has(d.slice(0, d.indexOf(':')).trim()));

    const kept = survivors.length
      ? `:root{\n  /* This app's own tokens, carried over. Remap them onto the studio\n     palette (--accent, --support…) when migrating this app layer. */\n  ${survivors.join(';\n  ')};\n}`
      : '';

    /* If this :root sits inside a media query whose only content is this
       block, drop the wrapper too rather than leaving `@media{ }` behind, unless something survived, in which case keep the wrapper around it. */
    const before = css.slice(i, root);
    const mq = before.lastIndexOf('@media');
    if (mq !== -1 && /@media[^{]*\{\s*$/.test(before.slice(mq))){
      const afterRoot = css.slice(end + 1);
      const closeMq = afterRoot.match(/^\s*\}/);
      if (closeMq){
        out += before.slice(0, mq) + (kept ? before.slice(mq) + kept + '}' : '');
        i = end + 1 + closeMq[0].length;
        continue;
      }
    }

    out += before + kept;
    i = end + 1;
  }

  return out.replace(/\n{3,}/g, '\n\n').trim();
}

/* ── Pruning the template layer ─────────────────────────────────────────── */
/*
 * All 23 apps were forked from one template, so most of what is in their style
 * blocks is the same 36 selectors restated. Those now live in the base, and if
 * they are left behind they sit AFTER it in the cascade and silently win, * the restyle would appear to do nothing.
 *
 * Measured across the portfolio: 36 selectors appear in 10+ apps (template),
 * 265 appear in exactly one (genuinely that app's own). This drops the former
 * and keeps the latter, which is the difference between a mechanical edit and
 * a judgement call. Everything inside an @media block is left alone, print
 * and responsive rules are frequently app-specific and worth a human read.
 */
const OWNED = new Set([
  '*', 'body', 'html', 'html,body', '.wrap',
  'button', '.btn', '.btn.primary', '.btn.danger', '.btn.small', '.btn.big',
  '.btn.ghost', '.btn.plain', '.btn.block', '.btn:disabled', '.btn:active',
  'header.app', 'header.app img', 'header.app h1', 'header.app .spacer',
  'a.tipbtn', '.hero', '.hero h2', '.hero p',
  'section.card', 'section.card h2', '.card', '.card h2', '.card .sub', '.sub',
  '.row', '.row>*', '.row > *',
  'label.f', 'label.f span', 'label.f>span', 'label.f > span',
  'textarea', 'select', 'input', '::placeholder',
  '.hint', '.footnote', '.small', '.em', '.muted',
  '.chip', '.chips', '.seg', '.seg button', '.seg button.active',
  '#toast', '#toast.show',
  'footer.colophon', 'footer.colophon a',
  '.hidden', '.sr-only', '.nowrap',
  'ul.plain', 'ul.plain li', 'ul.plain li:last-child', 'ul.plain .grow',
  'ol.plain', 'ol.plain li',
  'a', 'a:hover', 'hr', 'img', 'p',
]);

/** Compound selectors the base also owns, matched by shape rather than text. */
const OWNED_PATTERNS = [
  /^input\[type=/,                        // the long input-type list
  /focus-visible/,                        // old focus rules, the base replaces them
  /^\*,\s*\*::?before/,                   // box-sizing resets
  /^img,\s*svg/,
];

const isOwned = (sel) => {
  const s = sel.trim().replace(/\s+/g, ' ').toLowerCase();
  if (OWNED.has(s) || OWNED.has(s.replace(/ /g, ''))) return true;
  return OWNED_PATTERNS.some((re) => re.test(s));
};

/**
 * Walk top-level rules, dropping the ones the base owns.
 * Returns { css, dropped, kept } so the run can be reviewed rather than trusted.
 */
function pruneTemplateRules(css){
  let out = '', i = 0;
  const dropped = [], kept = [];

  while (i < css.length){
    // preserve comments verbatim
    if (css.startsWith('/*', i)){
      const end = css.indexOf('*/', i);
      if (end === -1){ out += css.slice(i); break; }
      out += css.slice(i, end + 2);
      i = end + 2;
      continue;
    }
    if (/\s/.test(css[i])){ out += css[i++]; continue; }

    const open = css.indexOf('{', i);
    if (open === -1){ out += css.slice(i); break; }

    let depth = 0, end = -1;
    for (let j = open; j < css.length; j++){
      if (css[j] === '{') depth++;
      else if (css[j] === '}' && --depth === 0){ end = j; break; }
    }
    if (end === -1){ out += css.slice(i); break; }

    const selector = css.slice(i, open).trim();
    const rule = css.slice(i, end + 1);

    // @media / @supports / @font-face and friends pass through untouched
    if (selector.startsWith('@') || isOwned(selector) === false){
      if (!selector.startsWith('@')) kept.push(selector);
      out += rule;
    } else {
      dropped.push(selector);
    }
    i = end + 1;
  }

  return { css: out.replace(/\n{3,}/g, '\n\n').trim(), dropped, kept };
}

/* ── Fonts and the service worker ───────────────────────────────────────── */
/*
 * A display font that is not in the service worker's precache list is a font
 * that vanishes the first time the user opens the app on a plane. Same for the
 * cache version: these workers are stale-while-revalidate, so without a bump a
 * returning user gets the OLD index.html on first load and reports that the
 * redesign never shipped.
 *
 * Both are mechanical, both are easy to forget, so they happen here.
 */
/**
 * Copy only when the bytes differ, and report whether anything moved.
 *
 * The caller needs that boolean: the service-worker cache version must bump
 * when an asset changes, and must NOT bump when nothing did, or every apply
 * run would inflate the version and push a pointless update to every user.
 */
function copyIfChanged(src, dest){
  mkdirSync(dirname(dest), { recursive: true });
  const next = readFileSync(src);
  if (existsSync(dest) && readFileSync(dest).equals(next)) return false;
  writeFileSync(dest, next);
  return true;
}

function installFont(slug, file){
  if (!file) return { path: null, changed: false };
  const rel = `fonts/${file}`;
  return { path: rel, changed: copyIfChanged(join(HERE, 'fonts', file), join(APPS, slug, rel)) };
}

/* The shared runtime, one copy per app so each service worker can cache it
   inside its own scope. Order is load order, and it matters: prefs must run
   first because it is the anti-flash pass. */
const RUNTIME = [
  { src: 'prefs.js', dest: 'sws-prefs.js' },
  { src: 'ui.js', dest: 'sws-ui.js' },
  { src: 'backup.js', dest: 'sws-backup.js' },
];

function installRuntime(slug){
  return RUNTIME.map((r) => ({
    path: r.dest,
    changed: copyIfChanged(join(HERE, r.src), join(APPS, slug, r.dest)),
  }));
}

/**
 * Point the page at that runtime.
 *
 * A CLASSIC, BLOCKING script in <head>, which is unusual enough to be worth
 * stating: it has to run before the first paint, or a user who chose Dark gets
 * a white flash on every navigation, in apps whose whole reason for existing
 * is frequently that it is 3am. A module would be deferred and a script at the
 * end of <body> would be far too late.
 *
 * External rather than inline because the strictest app here ships
 * `script-src 'self'`, which refuses an inline block outright.
 */
function addRuntimeTags(slug, html){
  let out = html;

  for (const r of RUNTIME){
    /* Match the src attribute, not the bare filename. The base layer's own
       comments mention these filenames, so a substring test finds a "tag" that
       is not there and silently skips every app. */
    const already = new RegExp(`<script[^>]+src=["']\\.?/?${r.dest.replace(/\./g, '\\.')}["']`);
    if (already.test(out)) continue;

    const tag = `<script src="${r.dest}"></script>`;

    if (out.includes('</head>')){
      out = out.replace('</head>', `${tag}\n</head>`);
    } else if (/<body[^>]*>/.test(out)){
      // A missing </head> is malformed but recoverable, the parser closes it
      // implicitly at <body>, so landing just before that is the same position.
      out = out.replace(/<body[^>]*>/, (m) => `${tag}\n${m}`);
    } else {
      console.log(`  !! ${slug}: nowhere to put ${r.dest}`);
    }
  }

  return out;
}

function updateServiceWorker(slug, assets){
  const swPath = join(APPS, slug, 'sw.js');
  if (!existsSync(swPath)) return 'no sw.js';
  let sw = readFileSync(swPath, 'utf8');
  const before = sw;
  const notes = [];

  const wanted = assets.filter(Boolean);
  if (wanted.length){
    // find the precache array, whatever this app happened to call it
    const m = sw.match(/const\s+(ASSETS|SHELL|FILES|PRECACHE|CORE)\s*=\s*\[([\s\S]*?)\]/);
    if (!m){
      notes.push('could not find precache array');
    } else {
      const missing = wanted.filter((p) => !m[2].includes(p));
      if (missing.length){
        // match the path style the existing entries use ('./x' vs 'x')
        const dotted = /["']\.\//.test(m[2]);
        const entries = missing.map((p) => `"${dotted ? './' : ''}${p}"`).join(', ');
        const joined = m[2].trimEnd().endsWith(',') ? ` ${entries}` : `, ${entries}`;
        sw = sw.replace(m[0], `const ${m[1]} = [${m[2].trimEnd()}${joined}]`);
        notes.push(`precached ${missing.join(' + ')}`);
      }
    }
  }

  // bump the trailing -vN of the cache name so returning users get the new shell
  const ver = sw.match(/(['"])([\w-]*?-v)(\d+)\1/);
  if (ver){
    sw = sw.replace(ver[0], `${ver[1]}${ver[2]}${Number(ver[3]) + 1}${ver[1]}`);
    notes.push(`cache ${ver[2]}${ver[3]} → ${ver[2]}${Number(ver[3]) + 1}`);
  } else {
    notes.push('no versioned cache name found, bump manually');
  }

  if (sw !== before) writeFileSync(swPath, sw);
  return notes.join(', ') || 'unchanged';
}

/**
 * Repaint the browser chrome to match the new palette.
 *
 * `theme-color` is the phone's address bar and `background_color` is the PWA
 * splash screen behind the icon while the app boots. Both still pointed at the
 * old flat grey, which means the very first and very last thing a user sees on
 * mobile would be the colour we just spent all this effort replacing.
 */
function repaintChrome(slug, html, palette){
  const light = palette.canvas;
  const dark = palette.darkCanvas;

  let next = html;
  if (/<meta name="theme-color"[^>]*prefers-color-scheme: ?light/.test(next)){
    next = next
      .replace(/(<meta name="theme-color" content=")[^"]*("[^>]*prefers-color-scheme: ?light[^>]*>)/, `$1${light}$2`)
      .replace(/(<meta name="theme-color" content=")[^"]*("[^>]*prefers-color-scheme: ?dark[^>]*>)/, `$1${dark}$2`);
  } else if (/<meta name="theme-color"/.test(next)){
    next = next.replace(
      /<meta name="theme-color"[^>]*>/,
      `<meta name="theme-color" content="${light}" media="(prefers-color-scheme: light)">\n` +
      `<meta name="theme-color" content="${dark}" media="(prefers-color-scheme: dark)">`);
  }

  const manifestPath = join(APPS, slug, 'manifest.webmanifest');
  if (existsSync(manifestPath)){
    try {
      const mf = JSON.parse(readFileSync(manifestPath, 'utf8'));
      if (mf.background_color !== light || mf.theme_color !== palette.accentDeep){
        mf.background_color = light;
        mf.theme_color = palette.accentDeep;
        writeFileSync(manifestPath, JSON.stringify(mf, null, 2) + '\n');
      }
    } catch { /* a malformed manifest is not this script's problem to guess at */ }
  }

  return next;
}

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const only = args.filter((a) => !a.startsWith('--'));

let changed = 0, skipped = 0;
const report = [];
const swNotes = [];

const FONTS = existsSync(join(HERE, 'out', 'fonts.json'))
  ? JSON.parse(readFileSync(join(HERE, 'out', 'fonts.json'), 'utf8'))
  : {};

const PALETTE = existsSync(join(HERE, 'out', 'palette.json'))
  ? JSON.parse(readFileSync(join(HERE, 'out', 'palette.json'), 'utf8'))
  : {};

for (const slug of Object.keys(SKINS)){
  if (only.length && !only.includes(slug)) continue;

  const htmlPath = join(APPS, slug, 'index.html');
  const cssPath = join(HERE, 'out', `${slug}.css`);
  if (!existsSync(htmlPath)){ console.log(`  !! ${slug}: no index.html`); continue; }
  if (!existsSync(cssPath)){ console.log(`  !! ${slug}: no built css, run build.mjs`); continue; }

  const html = readFileSync(htmlPath, 'utf8');
  const baseCss = readFileSync(cssPath, 'utf8');
  const base = `${BEGIN}\n${baseCss.trim()}\n${END}`;

  // Every custom property the base defines, discovered from the generated CSS
  // rather than hardcoded, so this cannot drift as tokens are added.
  const baseNames = new Set([...baseCss.matchAll(/(--[\w-]+)\s*:/g)].map((m) => m[1]));

  let next;

  if (html.includes(BEGIN) && html.includes(END)){
    /* Already applied, swap the base, leave the app layer alone. */
    const start = html.indexOf(BEGIN);
    const stop = html.indexOf(END) + END.length;
    next = html.slice(0, start) + base + html.slice(stop);
  } else {
    /* First run. Put the base at the top of the existing <style> block and
       fence everything that was already there below it, so nothing is lost
       and the app still renders while its own rules get migrated by hand. */
    const m = html.match(/<style>([\s\S]*?)<\/style>/);
    if (!m){ console.log(`  !! ${slug}: no <style> block found`); continue; }
    const stripped = stripLegacyTokens(m[1].trim(), baseNames);
    const { css: existing, dropped, kept } = pruneTemplateRules(stripped);
    report.push({ slug, dropped: dropped.length, kept: kept.length, keptSelectors: kept });
    next = html.replace(m[0], `<style>\n${base}\n\n${APP_LAYER}\n${existing}\n</style>`);
  }

  if (PALETTE[slug]) next = repaintChrome(slug, next, PALETTE[slug]);
  next = addRuntimeTags(slug, next);

  const htmlChanged = next !== html;

  if (checkOnly){
    if (!htmlChanged){ skipped++; continue; }
    changed++;
    console.log(`  would update  ${slug}`);
    continue;
  }

  /* Assets are written before the skip test on purpose. Once the script tags
     are in place the HTML compares equal on every later run, so a change to
     prefs.js, ui.js or a font would never reach the apps if this waited behind
     `htmlChanged`. Their own changed-flags then feed the version bump. */
  const font = installFont(slug, FONTS[slug]);
  const runtime = installRuntime(slug);

  if (!htmlChanged && !font.changed && !runtime.some((r) => r.changed)){ skipped++; continue; }

  if (htmlChanged) writeFileSync(htmlPath, next);
  swNotes.push(
    `${slug.padEnd(20)} ${(font.path ?? 'no font').padEnd(28)}  ` +
    `${updateServiceWorker(slug, [font.path, ...runtime.map((r) => r.path)])}`);

  changed++;
  console.log(`  updated  ${slug}`);
}

console.log(`\n${changed} changed, ${skipped} already current${checkOnly ? ' (check only, nothing written)' : ''}`);

if (swNotes.length){
  console.log('\nFonts and service workers:');
  for (const n of swNotes) console.log(`  ${n}`);
}

if (report.length){
  console.log('\nTemplate rules dropped (the base now owns them) vs app rules kept:');
  for (const r of report) console.log(`  ${r.slug.padEnd(20)} -${String(r.dropped).padStart(3)}  keeps ${r.kept}`);
  if (process.env.SHOW_KEPT){
    for (const r of report) console.log(`\n${r.slug}:\n  ${r.keptSelectors.join('\n  ')}`);
  }
}
