#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   SWS STUDIO — competitive brief

   Turns the per-app research JSON into something a person can read in one
   sitting: who owns each niche, what real users are angry about, what we have
   to build to be visibly better, and what the app should feel like.

     node design/brief.mjs      → design/findings/COMPETITIVE-BRIEF.md

   Only apps whose research has landed are included, and the file says which
   are missing rather than quietly leaving them out.
   ═══════════════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { SKINS } from './skins.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const F = join(HERE, 'findings');

const title = (s) => s.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');

const have = Object.keys(SKINS).filter((s) => existsSync(join(F, `${s}.research.json`)));
const missing = Object.keys(SKINS).filter((s) => !have.includes(s));

const all = have.map((s) => JSON.parse(readFileSync(join(F, `${s}.research.json`), 'utf8')));

/* ── Cross-app themes ───────────────────────────────────────────────────── */
const THEMES = [
  ['Forced account or sign-up', /account|sign ?up|log ?in|register|email wall/i],
  ['Ads and upsell in the workflow', /\bads?\b|advert|popup|pop-up|upsell|interstitial|sponsor/i],
  ['Subscription or paywall', /subscri|paywall|premium|free tier|trial|pay(wall|ment)?/i],
  ['Uploads / privacy worry', /upload|cloud|server|privacy|data (is|gets)? ?(sold|shared)|tracking/i],
  ['Export or download blocked', /export|watermark|download.*(lock|block|pay)|can.?t (save|export)/i],
  ['Bloat, clutter, too many taps', /clunk|slow|laggy|confus|clutter|bloat|too many taps|complicated/i],
  ['Print quality', /print|pdf.*(bad|ugly)|template/i],
  ['Too small to read', /tiny|too small|hard to read|font size|older adult|senior|eyes/i],
];

const complaints = all.flatMap((r) => (r.complaints ?? []).map((c) => ({ app: r.slug, ...c })));

const themeRows = THEMES.map(([name, re]) => {
  const hits = complaints.filter((c) => re.test(c.complaint));
  return { name, count: hits.length, apps: [...new Set(hits.map((h) => h.app))] };
}).sort((a, b) => b.apps.length - a.apps.length);

/* ── Per-app section ────────────────────────────────────────────────────── */
const section = (r) => {
  const skin = SKINS[r.slug];
  const comp = (r.competitors ?? []).map((c) =>
    `| ${c.name} | ${c.model} | ${c.note} |`).join('\n');

  const gripes = (r.complaints ?? []).map((c) =>
    `**${c.complaint}**\n<br>*Source:* ${c.source}\n<br>*We win if:* ${c.weWinIf}\n`).join('\n');

  return `
## ${title(r.slug)}

*${skin.note}*

**Who they are up against**

| Product | Model | Read |
|---|---|---|
${comp || '| — | — | no competitors recorded |'}

**What people actually complain about**

${gripes || '_none recorded_'}

**Table stakes** — absence of these reads as amateur

${(r.tableStakes ?? []).map((t) => `- ${t}`).join('\n') || '_none recorded_'}

**Where we can be visibly different**

${(r.differentiators ?? []).map((d) => `- ${d}`).join('\n') || '_none recorded_'}

**The user's state of mind**

${r.aesthetic?.emotionalContext ?? '_not recorded_'}

*Category looks like:* ${r.aesthetic?.categoryConventions ?? '—'}

*Should feel:* ${r.aesthetic?.recommendedFeel ?? '—'}

*Colour:* recommended **${r.colorRecommendation?.hueFamily ?? '—'}** — ${r.colorRecommendation?.rationale ?? ''} Avoid: ${r.colorRecommendation?.avoid ?? '—'}
<br>*Shipped:* hue ${skin.hue}, chroma ${skin.chroma}, ${skin.paper} paper, ${skin.voice} voice, ${skin.texture} texture.

*Confidence:* ${r.confidence ?? '—'}

---
`;
};

const doc = `# Competitive brief — Sky Wolf Studio

Generated by \`design/brief.mjs\` from the per-app research in this directory.
Every claim here came from a real web search: app-store reviews, Reddit threads,
forum posts and review sites. Where something could not be verified, the app's
*Confidence* line says so.

**${all.length} of ${Object.keys(SKINS).length} apps researched.**${missing.length ? `\n\nStill outstanding: ${missing.map(title).join(', ')}.` : ''}

---

## The pattern across every category

${complaints.length} distinct complaints were collected. Sorted by how many of
our categories they show up in:

| Complaint | Categories | Instances |
|---|---|---|
${themeRows.map((t) => `| ${t.name} | ${t.apps.length} | ${t.count} |`).join('\n')}

The top three are not features — they are the business models of the incumbents.
Every one of these companies has a payroll, and that payroll is why they must ask
for an account, run an ad, or put the export behind a card. We do not, and that
is the entire strategic position: **the promise is the product.**

Two consequences the design has to carry:

1. **Say it as an object, not a sentence.** Research repeatedly shows people do
   not believe a privacy claim written as grey body copy at the bottom of a
   page. The \`.trust\` component exists to make the promise look like a stamp
   on the thing rather than marketing.

2. **State the negative claim in plain words.** "No brand can pay to appear on
   your list" lands with a non-technical user in a way "we respect your privacy"
   never does.

And one hard UI rule, which came out of the reviews rather than any style guide:
competitors are engineering mis-taps. Cozi's upsell banner *"starts small and
increases in size just as users are about to click on a list."* Baby trackers put
promotional popups inside the log list, so a half-asleep parent taps an upgrade
prompt at 3am instead of the feed button. So: nothing appears over a primary
surface, and nothing in the thumb zone moves, grows or animates. Ever.

---
${all.map(section).join('\n')}`;

writeFileSync(join(F, 'COMPETITIVE-BRIEF.md'), doc);
console.log(`design/findings/COMPETITIVE-BRIEF.md — ${all.length} apps, ${complaints.length} complaints`);
if (missing.length) console.log(`still outstanding: ${missing.join(', ')}`);
